<a href="https://colab.research.google.com/github/Aleksandr-gitt/ControlWork/blob/main/%D0%94%D0%972.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import random
lst = ['robot'] * 10
lst += ['human'] * 10

In [3]:
random.shuffle(lst)

In [11]:
data = pd.DataFrame({'whoAmI':lst})
data.head(20)

   whoAmI
0   robot
1   human
2   human
3   human
4   robot
5   human
6   human
7   robot
8   robot
9   human
10  robot
11  robot
12  human
13  robot
14  human
15  robot
16  human
17  robot
18  human
19  robot

***Выше результат работы из ДЗ. ***

**1 способ**

In [6]:
for i in lst:
  data.loc[data['whoAmI']!=i,i] = '0'
else:
  data.loc[data['whoAmI']==i,i] = '1'

In [9]:
data.head()

  whoAmI robot human
0  robot     1     0
1  human     0     1
2  human     0     1
3  human     0     1
4  robot     1     0




**2 способ**

In [7]:
data.loc[data['whoAmI']=='human','human'] = '1'
data.loc[data['whoAmI']=='robot','human'] = '0'
data.loc[data['whoAmI']=='human','robot'] = '0'
data.loc[data['whoAmI']=='robot','robot'] = '1'

In [8]:
data.head()

  whoAmI robot human
0  robot     1     0
1  human     0     1
2  human     0     1
3  human     0     1
4  robot     1     0

In [10]:
data[['human','robot']]

   human robot
0      0     1
1      1     0
2      1     0
3      1     0
4      0     1
5      1     0
6      1     0
7      0     1
8      0     1
9      1     0
10     0     1
11     0     1
12     1     0
13     0     1
14     1     0
15     0     1
16     1     0
17     0     1
18     1     0
19     0     1